/// Flutter icons CustomIcons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData play = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData square_dashed__1_ = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData rules_alt = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData trophy_star = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alien = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData palette = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData house_blank = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData splotch = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData down = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData refresh = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubble = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData right = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData left = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hockey_mask = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData poo = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData luchador = IconData(0xe814, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask_carnival = IconData(0xe815, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData time_fast = IconData(0xe817, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData shoe_prints = IconData(0xe818, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData up = IconData(0xe819, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData duration_alt = IconData(0xe81a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_2 = IconData(0xe81b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lock = IconData(0xe81c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData usd_square = IconData(0xe81d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData unlock = IconData(0xe81e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_3 = IconData(0xe81f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_4 = IconData(0xe820, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData circle_1 = IconData(0xe821, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData test = IconData(0xe822, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tachometer_alt_average = IconData(0xe823, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bat = IconData(0xe824, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cube = IconData(0xe825, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beauty_mask = IconData(0xe826, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye = IconData(0xe827, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData alien_1 = IconData(0xe828, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData moon_stars = IconData(0xe829, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData brightness = IconData(0xe82a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData happy_face = IconData(0xe82b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bars_sort = IconData(0xe82c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spider = IconData(0xe82e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData spooky = IconData(0xe82f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eye_mask__2_ = IconData(0xe833, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mask = IconData(0xe834, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
